### ISSUE TITLE
Be able to use and store complex data exportable to json or yaml format

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#225]
forjj within Forjfiles and forjj secrets uses a collection of key/value pair and are expanded or used in forjj plugins to generate and deploy services (update/maintain).

Currently forjj works with strings only in a the value part of key/value pairs.

In short, key=value, where values is a string only.

In some cases, that string itself can be a json or a yaml format.
But forjj itself, still consider this data as a raw string and is not interpreted/managed/controlled by forjj.
So, we can introduce a mistake that will break the flow, because the expected string have to be a valid structure which could be extracted as json or yaml string or just extracted piece by piece where needed.

Ex:
```yaml
key:
  key1: value
  key2: 
    - element1
    - element2
```
Could be extracted by with go template with such syntax in forjj-jenkins plugin:
`{{ .Source.Key | to_json }}`

`{"key1": "value1", "key2": ["element1", "element2"]}`

or 
`{{ .Source.Key | to_yaml }}`

```yaml
key:
  key1: value
  key2: 
    - element1
    - element2
```

or 
`{{ index .Source.Key "key1" }}`

`values1`
