### ISSUE TITLE
Eliminates default values in Forjfile when forj is created from a Forjfile template

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#37]
Example here:
```yaml
projects:
  ec_tools:
    github-api-url: '{{ $Project := .Current.Name }}{{ (index .Forjfile.Repos $Project).UpstreamAPIUrl
      }}'
    github-repo: '{{ .Current.Name }}'
    github-repo-owner: '{{ $Project := .Current.Name }}{{ (index .Forjfile.Repos $Project).Owner
      }}'
    remote-type: '{{ $Project := .Current.Name }}{{ (index .Forjfile.Repos $Project).RemoteType
      }}'
```
all those are default values from the plugin. No need to save it in Forjfile.

This will facilitate Forjfile readibility.
