### ISSUE TITLE
Forjj update missed projects 

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#51]
The list projects under `projects` requires to have a `<repo_name>:`  with at least an empty `{}`

So, in the following example, only test2 is sent to the ci application.
```yaml
projects:
  test1:
  test2: {}
```
